set_property PACKAGE_PIN J16 [get_ports {rx_data_in_p[5]}]
set_property PACKAGE_PIN H19 [get_ports {rx_data_in_p[4]}]
set_property PACKAGE_PIN K17 [get_ports {rx_data_in_p[3]}]
set_property PACKAGE_PIN L17 [get_ports {rx_data_in_p[2]}]
set_property PACKAGE_PIN K19 [get_ports {rx_data_in_p[1]}]
set_property PACKAGE_PIN L20 [get_ports {rx_data_in_p[0]}]

set_property IOSTANDARD LVDS [get_ports {rx_data_in_p[5]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_p[4]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_p[3]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_p[2]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_p[1]}]
set_property IOSTANDARD LVDS [get_ports {rx_data_in_p[0]}]

set_property PACKAGE_PIN F17 [get_ports rx_clk_in_p]
set_property PACKAGE_PIN H18 [get_ports rx_frame_in_p]

set_property IOSTANDARD LVDS [get_ports rx_clk_in_p]
set_property IOSTANDARD LVDS [get_ports rx_frame_in_p]

set_property PACKAGE_PIN D16 [get_ports {tx_data_out_p[5]}]
set_property PACKAGE_PIN C13 [get_ports {tx_data_out_p[4]}]
set_property PACKAGE_PIN L15 [get_ports {tx_data_out_p[3]}]
set_property PACKAGE_PIN G15 [get_ports {tx_data_out_p[2]}]
set_property PACKAGE_PIN G18 [get_ports {tx_data_out_p[1]}]
set_property PACKAGE_PIN A13 [get_ports {tx_data_out_p[0]}]

set_property IOSTANDARD LVDS [get_ports {tx_data_out_p[5]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_p[4]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_p[3]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_p[2]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_p[1]}]
set_property IOSTANDARD LVDS [get_ports {tx_data_out_p[0]}]

set_property PACKAGE_PIN E18 [get_ports tx_clk_out_p]
set_property PACKAGE_PIN H16 [get_ports tx_frame_out_p]

set_property IOSTANDARD LVDS [get_ports tx_clk_out_p]
set_property IOSTANDARD LVDS [get_ports tx_frame_out_p]

set_property PACKAGE_PIN B8 [get_ports adc9361_spi_clk]
set_property IOSTANDARD LVCMOS18 [get_ports adc9361_spi_clk]
set_property PACKAGE_PIN B9 [get_ports adc9361_spi_ss]
set_property IOSTANDARD LVCMOS18 [get_ports adc9361_spi_ss]
set_property PACKAGE_PIN A8 [get_ports adc9361_spi_miso]
set_property IOSTANDARD LVCMOS18 [get_ports adc9361_spi_miso]
set_property PACKAGE_PIN A7 [get_ports adc9361_spi_mosi]
set_property IOSTANDARD LVCMOS18 [get_ports adc9361_spi_mosi]

set_property PACKAGE_PIN D17 [get_ports adc9361_enable]
set_property IOSTANDARD LVCMOS18 [get_ports adc9361_enable]
set_property PACKAGE_PIN C17 [get_ports adc9361_txnrx]
set_property IOSTANDARD LVCMOS18 [get_ports adc9361_txnrx]
set_property PACKAGE_PIN M13 [get_ports adc9361_rst]
set_property IOSTANDARD LVCMOS18 [get_ports adc9361_rst]
set_property PACKAGE_PIN D12 [get_ports adc9361_en_agc]
set_property IOSTANDARD LVCMOS18 [get_ports adc9361_en_agc]
set_property PACKAGE_PIN C11 [get_ports adc9361_sync_in]
set_property IOSTANDARD LVCMOS18 [get_ports adc9361_sync_in]

set_property PACKAGE_PIN A11 [get_ports {adc9361_ctr_o[7]}]
set_property PACKAGE_PIN B11 [get_ports {adc9361_ctr_o[6]}]
set_property PACKAGE_PIN H12 [get_ports {adc9361_ctr_o[5]}]
set_property PACKAGE_PIN H13 [get_ports {adc9361_ctr_o[4]}]
set_property PACKAGE_PIN A10 [get_ports {adc9361_ctr_o[3]}]
set_property PACKAGE_PIN B10 [get_ports {adc9361_ctr_o[2]}]
set_property PACKAGE_PIN F12 [get_ports {adc9361_ctr_o[1]}]
set_property PACKAGE_PIN E12 [get_ports {adc9361_ctr_o[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {adc9361_ctr_o[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc9361_ctr_o[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc9361_ctr_o[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc9361_ctr_o[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc9361_ctr_o[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc9361_ctr_o[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc9361_ctr_o[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc9361_ctr_o[0]}]

set_property PACKAGE_PIN C6 [get_ports {adc9361_ctr_i[3]}]
set_property PACKAGE_PIN C7 [get_ports {adc9361_ctr_i[2]}]
set_property PACKAGE_PIN A6 [get_ports {adc9361_ctr_i[1]}]
set_property PACKAGE_PIN B6 [get_ports {adc9361_ctr_i[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {adc9361_ctr_i[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc9361_ctr_i[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc9361_ctr_i[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {adc9361_ctr_i[0]}]